#z3
SELECT ?person ?personLabel ?high ?deathPlaceLabel
WHERE
{
  ?person  wdt:P19 ?birthCity;
           wdt:P20 ?deathPlace.
  ?birthCity wdt:P17  wd:Q36.
  ?deathPlace p:P2044/psn:P2044/wikibase:quantityAmount ?high.
  FILTER(?high > 8000)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }

}
  ORDER BY ASC(?stateLabel)
limit 200