#z4
SELECT ?nationalityLabel (COUNT(DISTINCT(?person)) as ?count) 
WHERE {
  #jest politykiem
  ?person wdt:P106 wd:Q82955.
  #urodzony w polsce
  ?person wdt:P19 ?birthCity.
  ?birthCity wdt:P17 wd:Q36.
  #ma label po polsku
  ?person rdfs:label ?personLabel.
  FILTER(LANG(?personLabel) = "pl")
  #nie ma obywatelstwa polskiego
  ?person wdt:P27 ?nationality.
  filter(?nationality != wd:Q36)
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "pl". }
}
group by ?nationalityLabel

ORDER BY DESC(?count)